sonar.projectKey=alicevision_AliceVision
sonar.organization=alicevision

sonar.projectName=AliceVision
sonar.projectVersion=1.0

# Source & test directories
sonar.sources=src

# Exclusions
sonar.exclusions=**/build/**,**/third_party/**,**/*.pb.cc,**/*.pb.h

# Cache for faster analysis
sonar.cfamily.cache.enabled=true
sonar.cfamily.analysisCache.mode=fs 
sonar.cfamily.analysisCache.path=/root/.sonar/cache 
sonar.cfamily.threads=4

#sonar.verbose=true