# This file contains a helper macro to pass through as many CLI options as
# possible to the AliceVision sub-build when used in the dependency build
# orchestrator.
# This mainly includes all the options which might be defined in
# src/CMakeLists.txt and therefore would be lost in this case.
#
# Provides: AV_BUILD_FLAGS, AV_COMPONENT_FLAGS, AV_TOPLEVEL_FLAGS

macro(av_merge_configure_options)

    # Build the required flags to pass through
    set(AV_BUILD_FLAGS
        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        -DALICEVISION_USE_RPATH=${ALICEVISION_USE_RPATH}
        -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}
        -DBUILD_APPLE_FRAMEWORKS=${BUILD_APPLE_FRAMEWORKS}
        -DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}
        -DALICEVISION_BUNDLE_PREFIX=${ALICEVISION_BUNDLE_PREFIX}
    )
    set(AV_COMPONENT_FLAGS
        -DALICEVISION_BUILD_DOC=OFF
        -DALICEVISION_BUILD_TESTS=${ALICEVISION_BUILD_TESTS}
        -DALICEVISION_INSTALL_MESHROOM_PLUGIN=${ALICEVISION_INSTALL_MESHROOM_PLUGIN}
    )
    set(AV_TOPLEVEL_FLAGS
        -DAV_EIGEN_MEMORY_ALIGNMENT=${AV_EIGEN_MEMORY_ALIGNMENT}
        -DALICEVISION_USE_CUDA=${AV_USE_CUDA}
        -DALICEVISION_USE_OPENCV:BOOL=${AV_BUILD_OPENCV}
        -DALICEVISION_BUILD_SWIG_BINDING:BOOL=${AV_BUILD_SWIG}
    )

    # FIXME: Ideally we should move all options to the top-level CMakeLists.txt
    # file. However, this approach provides backwards-compatibility and sets
    # the flags as always, but enables the user to override them manually.
    # As the last option specified takes precedence on the CLI, we only pass
    # these flags if they are defined (= the user specified them on the CLI).
    # The following flags are only added if specified for now
    if(DEFINED ALICEVISION_REMOVE_ABSOLUTE)
        list(APPEND AV_BUILD_FLAGS -DALICEVISION_REMOVE_ABSOLUTE=${ALICEVISION_REMOVE_ABSOLUTE})
    endif()
    if(DEFINED ALICEVISION_REQUIRE_CERES_WITH_SUITESPARSE)
        list(APPEND AV_MISC_FLAGS -DALICEVISION_REQUIRE_CERES_WITH_SUITESPARSE=${ALICEVISION_REQUIRE_CERES_WITH_SUITESPARSE})
    endif()
    if(DEFINED ALICEVISION_REQUIRE_CERES_WITH_ACCELERATESPARSE)
        list(APPEND AV_MISC_FLAGS -DALICEVISION_REQUIRE_CERES_WITH_ACCELERATESPARSE=${ALICEVISION_REQUIRE_CERES_WITH_ACCELERATESPARSE})
    endif()
    if(DEFINED ALICEVISION_USE_MESHSDFILTER)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_USE_MESHSDFILTER=${ALICEVISION_USE_MESHSDFILTER})
    endif()
    if(DEFINED ALICEVISION_USE_OCVSIFT)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_USE_OCVSIFT=${ALICEVISION_USE_OCVSIFT})
    endif()
    if(DEFINED ALICEVISION_USE_OPENCV_CONTRIB)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_USE_OPENCV_CONTRIB=${ALICEVISION_USE_OPENCV_CONTRIB})
    endif()
    if(DEFINED ALICEVISION_USE_OPENCV)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_USE_OPENCV=${ALICEVISION_USE_OPENCV})
    endif()
    if(DEFINED ALICEVISION_USE_ONNX_GPU)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_USE_ONNX_GPU=${ALICEVISION_USE_ONNX_GPU})
    endif()
    if(DEFINED ALICEVISION_USE_ONNX)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_USE_ONNX=${ALICEVISION_USE_ONNX})
    endif()
    if(DEFINED ALICEVISION_USE_UNCERTAINTYTE)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_USE_UNCERTAINTYTE=${ALICEVISION_USE_UNCERTAINTYTE})
    endif()
    if(DEFINED ALICEVISION_USE_ALEMBIC)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_USE_ALEMBIC=${ALICEVISION_USE_ALEMBIC})
    endif()
    if(DEFINED ALICEVISION_USE_POPSIFT)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_USE_POPSIFT=${ALICEVISION_USE_POPSIFT})
    endif()
    if(DEFINED ALICEVISION_USE_APRILTAG)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_USE_APRILTAG=${ALICEVISION_USE_APRILTAG})
    endif()
    if(DEFINED ALICEVISION_USE_CCTAG)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_USE_CCTAG=${ALICEVISION_USE_CCTAG})
    endif()
    if(DEFINED ALICEVISION_USE_OPENMP)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_USE_OPENMP=${ALICEVISION_USE_OPENMP})
    endif()
    if(DEFINED ALICEVISION_USE_CUDA)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_USE_CUDA=${ALICEVISION_USE_CUDA})
    endif()
    if(DEFINED ALICEVISION_BUILD_LIDAR)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_BUILD_LIDAR=${ALICEVISION_BUILD_LIDAR})
    endif()
    if(DEFINED ALICEVISION_BUILD_SWIG_BINDING)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_BUILD_SWIG_BINDING=${ALICEVISION_BUILD_SWIG_BINDING})
    endif()
    if(DEFINED ALICEVISION_BUILD_DOC)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_BUILD_DOC=${ALICEVISION_BUILD_DOC})
    endif()
    if(DEFINED ALICEVISION_BUILD_COVERAGE)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_BUILD_COVERAGE=${ALICEVISION_BUILD_COVERAGE})
    endif()
    if(DEFINED ALICEVISION_BUILD_SOFTWARE)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_BUILD_SOFTWARE=${ALICEVISION_BUILD_SOFTWARE})
    endif()
    if(DEFINED ALICEVISION_BUILD_PANORAMA)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_BUILD_PANORAMA=${ALICEVISION_BUILD_PANORAMA})
    endif()
    if(DEFINED ALICEVISION_BUILD_PHOTOMETRICSTEREO)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_BUILD_PHOTOMETRICSTEREO=${ALICEVISION_BUILD_PHOTOMETRICSTEREO})
    endif()
    if(DEFINED ALICEVISION_BUILD_SEGMENTATION)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_BUILD_SEGMENTATION=${ALICEVISION_BUILD_SEGMENTATION})
    endif()
    if(DEFINED ALICEVISION_BUILD_HDR)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_BUILD_HDR=${ALICEVISION_BUILD_HDR})
    endif()
    if(DEFINED ALICEVISION_BUILD_MVS)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_BUILD_MVS=${ALICEVISION_BUILD_MVS})
    endif()
    if(DEFINED ALICEVISION_BUILD_SFM)
        list(APPEND AV_TOPLEVEL_FLAGS -DALICEVISION_BUILD_SFM=${ALICEVISION_BUILD_SFM})
    endif()

endmacro()
