ARG TRISQUEL_VERSION
FROM kpengboy/trisquel:${TRISQUEL_VERSION}

# Set it here here as they are not available in the RUN commands if set before FROM...
ARG UBUNTU_CODENAME

LABEL maintainer="AliceVision Team alicevision-team@googlegroups.com"

# This docker file is mainly for building the dependencies for testing on a FSF compliant distro. 
# For now, it downloads and installs CUDA
# TODO: Deactivate CUDA once the Vulkan port is done ;-)

# Install all compilation tools
# The Kitware repo provides a recent cmake
RUN apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
		wget \
		software-properties-common && \
	wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc | gpg --dearmor - > /etc/apt/trusted.gpg.d/kitware.gpg && \
	apt-add-repository "deb https://apt.kitware.com/ubuntu/ $UBUNTU_CODENAME main" && \
	apt-get clean && \
	apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
		build-essential \
		git \
		unzip \
		yasm \
		pkg-config \
		libtool \
		libssl-dev \
		nasm \
		automake \
		cmake \
		gfortran

ENV AV_DEV=/opt/AliceVision_git \
    AV_BUILD=/tmp/AliceVision_build \
    AV_INSTALL=/opt/AliceVision_install \
    PATH="${PATH}:${AV_BUNDLE}"

COPY dl/vlfeat_K80L3.SIFT.tree ${AV_INSTALL}/share/aliceVision/
RUN echo "export ALICEVISION_VOCTREE=${AV_INSTALL}/share/aliceVision/vlfeat_K80L3.SIFT.tree" > /etc/profile.d/alicevision.sh

COPY CMakeLists.txt ${AV_DEV}/

COPY dl/deps ${AV_BUILD}/external/download/

WORKDIR "${AV_BUILD}"
RUN cmake "${AV_DEV}" \
     -DCMAKE_BUILD_TYPE=Release \
     -DALICEVISION_BUILD_DEPENDENCIES:BOOL=ON \
     -DAV_BUILD_ALICEVISION:BOOL=OFF \
     -DAV_USE_CUDA:BOOL=ON \
     -DAV_BUILD_CUDA:BOOL=ON \
     -DCMAKE_INSTALL_PREFIX="${AV_INSTALL}"

# Symlink lib64 to lib as qtOIIO expects to find OIIO in lib64
# Also, CUDA does not install correctly if lib64 is a symlink
RUN mkdir -p "${AV_INSTALL}/lib64" && \
        ln -s lib64 "${AV_INSTALL}/lib"

WORKDIR "${AV_BUILD}"
#RUN make -j"$(nproc)" zlib
#RUN make -j"$(nproc)" geogram
#RUN make -j"$(nproc)" tbb
#RUN make -j"$(nproc)" eigen
#RUN make -j"$(nproc)" opengv
#RUN make -j"$(nproc)" lapack
#RUN make -j"$(nproc)" suitesparse
#RUN make -j"$(nproc)" ceres
#RUN make -j"$(nproc)" openexr
#RUN make -j"$(nproc)" tiff
#RUN make -j"$(nproc)" png
#RUN make -j"$(nproc)" turbojpeg
#RUN make -j"$(nproc)" libraw
#RUN make -j"$(nproc)" boost
#RUN make -j"$(nproc)" openimageio
#RUN make -j"$(nproc)" alembic
#RUN make -j"$(nproc)" popsift
#RUN make -j"$(nproc)" opencv
#RUN make -j"$(nproc)" cctag

RUN cmake --build . -j "$(nproc)" && \
    mv "${AV_INSTALL}/bin" "${AV_INSTALL}/bin-deps" && \
    rm -rf "${AV_BUILD}"

