ARG CUDA_VERSION=11.8.0
ARG UBUNTU_VERSION=22.04
FROM nvidia/cuda:${CUDA_VERSION}-devel-ubuntu${UBUNTU_VERSION}
LABEL maintainer="Hossam Hammady <github@hammady.net>"

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        git \
        build-essential \
        cmake \
        libboost-all-dev \
        libeigen3-dev \
        libflann-dev \
        libjpeg-dev \
        libturbojpeg0-dev \
        libpng-dev \
        libtiff-dev \
        libraw-dev \
        libassimp-dev \
        libceres-dev \
        libopenexr-dev \
        libimath-dev \
        libopenimageio-dev \
        libxxf86vm1 \
        libxxf86vm-dev \
        libxi-dev \
        libxrandr-dev \
        graphviz \
        libapriltag-dev \
        liblapack-dev \
        libopencv-dev \
        libpcl-dev \
        libsuitesparse-dev \
        ffmpeg \
        libvpx-dev \
        zlib1g-dev

RUN mkdir /tmp/AliceVision_build && \
    mkdir /opt/AliceVision_install && \
    mkdir /opt/AliceVision_bundle

ENV AV_DEV=/home \
    AV_BUILD=/tmp/AliceVision_build \
    AV_INSTALL=/opt/AliceVision_install \
    AV_BUNDLE=/opt/AliceVision_bundle \
    PATH="${PATH}:${AV_BUNDLE}"

COPY CMakeLists.txt ${AV_DEV}/
COPY src ${AV_DEV}/src

WORKDIR ${AV_BUILD}

# Install AliceVision dependencies
RUN mkdir build && cd build && \
    cmake \
        -DALICEVISION_BUILD_DEPENDENCIES=ON \
        -DAV_BUILD_ALICEVISION=OFF \
        -DAV_BUILD_ZLIB=OFF \
        -DAV_BUILD_ASSIMP=OFF \
        -DAV_BUILD_TIFF=OFF \
        -DAV_BUILD_JPEG=OFF \
        -DAV_BUILD_PNG=OFF \
        -DAV_BUILD_LIBRAW=OFF \
        -DAV_BUILD_APRILTAG=OFF \
        -DAV_BUILD_OPENCV=OFF \
        -DAV_BUILD_LAPACK=OFF \
        -DAV_BUILD_PCL=OFF \
        -DAV_BUILD_SUITESPARSE=OFF \
        -DAV_BUILD_FFMPEG=OFF \
        -DAV_BUILD_VPX=OFF \
        -DCMAKE_INSTALL_PREFIX:PATH="${AV_INSTALL}" \
        -DCMAKE_MODULE_PATH:PATH=/usr/share/eigen3/cmake \
        -DAV_BUILD_DEPENDENCIES_PARALLEL=0 \
        ${AV_DEV} && \
    make -j$(nproc)

# Install AliceVision
RUN cd build && \
    cmake \
        -DALICEVISION_BUILD_DEPENDENCIES=OFF \
        -DAV_BUILD_ALICEVISION=ON \
        -DCUDA_TOOLKIT_ROOT_DIR:PATH=/usr/local/cuda-${CUDA_VERSION%.*} \
        -DTARGET_ARCHITECTURE=core \
        -DCMAKE_PREFIX_PATH:PATH="${AV_INSTALL}" \
        -DCMAKE_INSTALL_PREFIX:PATH="${AV_INSTALL}" \
        -DALICEVISION_BUNDLE_PREFIX="${AV_BUNDLE}" \
        ${AV_DEV} && \
    make -j$(nproc)



