# Preamble
ARG CUDA_VERSION=11.8.0
ARG UBUNTU_VERSION=22.04
FROM nvidia/cuda:${CUDA_VERSION}-devel-ubuntu${UBUNTU_VERSION}
LABEL maintainer="Hossam Hammady <github@hammady.net>"

# Install system dependencies
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        git \
        build-essential \
        cmake \
        libboost-all-dev \
        libeigen3-dev \
        libflann-dev \
        libjpeg-dev \
        libturbojpeg0-dev \
        libpng-dev \
        libtiff-dev \
        libraw-dev \
        libassimp-dev \
        libceres-dev \
        libopenexr-dev \
        libopenimageio-dev \
        libxxf86vm1 \
        libxxf86vm-dev \
        libxi-dev \
        libxrandr-dev \
        graphviz \
        libapriltag-dev \
        liblapack-dev \
        libopencv-dev \
        libpcl-dev \
        libsuitesparse-dev \
        ffmpeg \
        libvpx-dev \
        zlib1g-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set environment variables
ENV AV_DEV=/home \
    AV_BUILD=/tmp/AliceVision_build \
    AV_INSTALL=/opt/AliceVision_install \
    PATH="${PATH}:${AV_INSTALL}/bin" \
    LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${AV_INSTALL}/lib" \
    ALICEVISION_ROOT="${AV_INSTALL}" \
    ALICEVISION_SENSOR_DB="${AV_INSTALL}/share/aliceVision/cameraSensors.db"

# Copy AliceVision source code
COPY CMakeLists.txt ${AV_DEV}/
COPY src ${AV_DEV}/src

# Create build and install directories
RUN mkdir ${AV_BUILD} ${AV_INSTALL}

WORKDIR ${AV_BUILD}

# Install AliceVision dependencies
RUN cmake \
        -DALICEVISION_BUILD_DEPENDENCIES=ON \
        -DAV_BUILD_ALICEVISION=OFF \
        -DAV_BUILD_ZLIB=OFF \
        -DAV_BUILD_ASSIMP=OFF \
        -DAV_BUILD_TIFF=OFF \
        -DAV_BUILD_JPEG=OFF \
        -DAV_BUILD_PNG=OFF \
        -DAV_BUILD_LIBRAW=OFF \
        -DAV_BUILD_APRILTAG=OFF \
        -DAV_BUILD_OPENCV=OFF \
        -DAV_BUILD_LAPACK=OFF \
        -DAV_BUILD_PCL=OFF \
        -DAV_BUILD_SUITESPARSE=OFF \
        -DAV_BUILD_FFMPEG=OFF \
        -DAV_BUILD_VPX=OFF \
        -DCMAKE_INSTALL_PREFIX:PATH="${AV_INSTALL}" \
        -DCMAKE_MODULE_PATH:PATH=/usr/share/eigen3/cmake \
        -DAV_BUILD_DEPENDENCIES_PARALLEL=0 \
        ${AV_DEV} && \
    make -j$(nproc)

# Install AliceVision
RUN cmake \
        -DALICEVISION_BUILD_DEPENDENCIES=OFF \
        -DAV_BUILD_ALICEVISION=ON \
        -DCUDA_TOOLKIT_ROOT_DIR:PATH=/usr/local/cuda-${CUDA_VERSION%.*} \
        -DTARGET_ARCHITECTURE=core \
        -DCMAKE_PREFIX_PATH:PATH="${AV_INSTALL}" \
        -DCMAKE_INSTALL_PREFIX:PATH="${AV_INSTALL}" \
        ${AV_DEV} && \
    make -j$(nproc) && \
    make -j$(nproc) install

# Clean up
WORKDIR ${AV_INSTALL}
RUN rm -rf ${AV_BUILD}/* ${AV_DEV}/*
