name: Continuous Integration

on:
  push:
    branches:
      - master
      - develop
    # Skip jobs when only documentation files are changed
    paths-ignore:
      - '**.md'
      - '**.rst'
      - '**.db'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'
      - '**.db'
      - 'docs/**'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["alicevision/alicevision-deps:2025.03.27-rocky9-cuda12.1.1"]
    container:
      image: ${{ matrix.container }}
    env:
      DEPS_INSTALL_DIR: /opt/AliceVision_install
      BUILD_TYPE: Release
      CTEST_OUTPUT_ON_FAILURE: 1
      ALICEVISION_ROOT: ${{ github.workspace }}/../AV_install
      ALICEVISION_SENSOR_DB: ${{ github.workspace }}/../AV_install/share/aliceVision/cameraSensors.db
      ALICEVISION_LENS_PROFILE_INFO: ""
      BUILD_CCTAG: "${{ matrix.container == 'alicevision/alicevision-deps:2025.03.27-ubuntu22.04-cuda12.1.1' && 'ON' || 'OFF' }}"
    steps:
      - uses: actions/checkout@v1
      
      - name: Set AGENT_TOOLSDIRECTORY
        run: echo "AGENT_TOOLSDIRECTORY=${{ runner.temp }}/tools-rocky9" >>   $GITHUB_ENV
        
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Prepare File Tree
        run: |
          mkdir ./build
          mkdir ./build_as_3rdparty
          mkdir ./functional_tests
          mkdir ../AV_install

      - name: Functional Tests - PanoramaFisheyeHdr Pipeline
        working-directory: ./functional_tests
        run: |
          python3 -m pip install psutil

          # Clone required repos
          git clone --branch develop https://github.com/alicevision/Meshroom.git
          git clone --branch main https://github.com/alicevision/dataset_panoramaFisheyeHdr.git
          cd Meshroom/
          meshroom_avBranch=$(git ls-remote --heads https://github.com/alicevision/Meshroom.git $GITHUB_HEAD_REF | cut -f 1)
          if [ $meshroom_avBranch != "" ]; then git checkout $meshroom_avBranch; echo "Use Meshroom/$GITHUB_HEAD_REF"; fi

          # Set environment variables specific to Meshroom
          export MESHROOM_INSTALL_DIR=$PWD
          export MESHROOM_NODES_PATH=${MESHROOM_NODES_PATH}:${ALICEVISION_ROOT}/share/meshroom
          export MESHROOM_PIPELINE_TEMPLATES_PATH=${MESHROOM_PIPELINE_TEMPLATES_PATH}:${ALICEVISION_ROOT}/share/meshroom

          # Set environment variables to find executables and libraries
          export PYTHONPATH=$PWD:${ALICEVISION_ROOT}/bin:${PYTHONPATH}
          export PATH=$PATH:${ALICEVISION_ROOT}/bin
          export LD_LIBRARY_PATH=${ALICEVISION_ROOT}/lib:${ALICEVISION_ROOT}/lib64:${DEPS_INSTALL_DIR}/lib64:${DEPS_INSTALL_DIR}/lib:${LD_LIBRARY_PATH}

          # Run the test pipeline
          
          cd bin/
          mkdir ./outputData
          python meshroom_batch -i $PWD/../../dataset_panoramaFisheyeHdr/RAW -p dummy -o $PWD/../outputData
          

  
