name: Docker

on:
  push:
    branches:
      - master
      - develop
      - gh-actions-docker # TODO remove before creating a PR
    # Skip jobs when only documentation files are changed
    paths-ignore:
      - '**.md'
      - '**.rst'
      - '**.db'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'
      - '**.db'
      - 'docs/**'

env:
  REPO_OWNER: ${{ github.repository_owner }}
  CUDA_VERSION: "11.3.1"
  DOCKER_PUSH: "true"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      UBUNTU_VERSION: "20.04"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: docker/build-ubuntu.sh

  centos:
    runs-on: ubuntu-latest
    env:
      CENTOS_VERSION: "7"
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: docker/build-centos.sh
